import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const KB_DIR = "nimbusstack-knowledge-base";
export const OUT = "src/kb/corpus.gen.ts";

export function renderCorpus(dir = KB_DIR): string {
  const files = readdirSync(dir).filter((f) => f.endsWith(".md")).sort();
  const corpus = files.map((file) => ({ file, content: readFileSync(join(dir, file), "utf8") }));
  return (
    "// Generated by scripts/gen-corpus.ts from nimbusstack-knowledge-base/. Do not edit.\n" +
    `export const CORPUS: ReadonlyArray<{ file: string; content: string }> = ${JSON.stringify(corpus, null, 2)};\n`
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(OUT, renderCorpus());
  console.log(`wrote ${OUT}`);
}
